[2025-06-08T19:50:32.904+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: news_ingestion_pipeline.filter_existing_articles manual__2025-06-08T19:50:27.102609+00:00 [queued]>
[2025-06-08T19:50:32.911+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: news_ingestion_pipeline.filter_existing_articles manual__2025-06-08T19:50:27.102609+00:00 [queued]>
[2025-06-08T19:50:32.912+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-08T19:50:32.923+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): filter_existing_articles> on 2025-06-08 19:50:27.102609+00:00
[2025-06-08T19:50:32.930+0000] {standard_task_runner.py:60} INFO - Started process 113 to run task
[2025-06-08T19:50:32.934+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'news_ingestion_pipeline', 'filter_existing_articles', 'manual__2025-06-08T19:50:27.102609+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/rss_scrap_dag.py', '--cfg-path', '/tmp/tmp7v_lchj5']
[2025-06-08T19:50:32.937+0000] {standard_task_runner.py:88} INFO - Job 77: Subtask filter_existing_articles
[2025-06-08T19:50:32.993+0000] {task_command.py:423} INFO - Running <TaskInstance: news_ingestion_pipeline.filter_existing_articles manual__2025-06-08T19:50:27.102609+00:00 [running]> on host 44e96206a18a
[2025-06-08T19:50:33.056+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='news_ingestion_pipeline' AIRFLOW_CTX_TASK_ID='filter_existing_articles' AIRFLOW_CTX_EXECUTION_DATE='2025-06-08T19:50:27.102609+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-08T19:50:27.102609+00:00'
[2025-06-08T19:50:33.521+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rss_scrap_dag.py", line 46, in step_2_filter_existing
    existing_ids = filter_existing_articles(uniques, project, dataset, table)
  File "/opt/airflow/src/ingestion/rss_filter.py", line 34, in filter_existing_articles
    existing_ids = get_existing_ids_from_bigquery(project_id, dataset_id, table_id, all_ids)
  File "/opt/airflow/src/ingestion/rss_filter.py", line 22, in get_existing_ids_from_bigquery
    query_job = client.query(query)
  File "/home/airflow/.local/lib/python3.10/site-packages/google/cloud/bigquery/client.py", line 3387, in query
    return _job_helpers.query_jobs_insert(
  File "/home/airflow/.local/lib/python3.10/site-packages/google/cloud/bigquery/_job_helpers.py", line 158, in query_jobs_insert
    future = do_query()
  File "/home/airflow/.local/lib/python3.10/site-packages/google/cloud/bigquery/_job_helpers.py", line 135, in do_query
    query_job._begin(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.10/site-packages/google/cloud/bigquery/job/query.py", line 1379, in _begin
    super(QueryJob, self)._begin(client=client, retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.10/site-packages/google/cloud/bigquery/job/base.py", line 740, in _begin
    api_response = client._call_api(
  File "/home/airflow/.local/lib/python3.10/site-packages/google/cloud/bigquery/client.py", line 818, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.10/site-packages/google/api_core/retry.py", line 372, in retry_wrapped_func
    return retry_target(
  File "/home/airflow/.local/lib/python3.10/site-packages/google/api_core/retry.py", line 207, in retry_target
    result = target()
  File "/home/airflow/.local/lib/python3.10/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/ton-projet/jobs?prettyPrint=false: ProjectId must be non-empty

Location: None
Job ID: 1c669db6-935f-4a7d-a412-64227edec28b

[2025-06-08T19:50:33.539+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=news_ingestion_pipeline, task_id=filter_existing_articles, execution_date=20250608T195027, start_date=20250608T195032, end_date=20250608T195033
[2025-06-08T19:50:33.551+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 77 for task filter_existing_articles (400 POST https://bigquery.googleapis.com/bigquery/v2/projects/ton-projet/jobs?prettyPrint=false: ProjectId must be non-empty

Location: None
Job ID: 1c669db6-935f-4a7d-a412-64227edec28b
; 113)
[2025-06-08T19:50:33.588+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-08T19:50:33.609+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
